'use client';
// Exports a system's compliance dossier as a PDF evidence package for a notified
// body / market-surveillance authority. Mirrors the react-pdf approach in
// src/components/AuditReport.tsx (FDA), kept separate so that file is untouched.
import { useState } from 'react';
import { Download } from 'lucide-react';
import { Document, Page, Text, View, StyleSheet, pdf } from '@react-pdf/renderer';
import { GhostButton, Spinner } from './ui';
import { RISK_LEVELS } from '@/lib/ai-act/constants';
import { completionPercentage } from '@/lib/ai-act/annex-iv-sections';

const s = StyleSheet.create({
  page: { padding: 40, fontSize: 10, color: '#1a1a1a', fontFamily: 'Helvetica' },
  h1: { fontSize: 18, fontFamily: 'Helvetica-Bold', marginBottom: 4 },
  meta: { fontSize: 9, color: '#666', marginBottom: 16 },
  h2: { fontSize: 12, fontFamily: 'Helvetica-Bold', marginTop: 16, marginBottom: 6, borderBottom: '1 solid #ddd', paddingBottom: 3 },
  row: { flexDirection: 'row', marginBottom: 3 },
  label: { width: 130, color: '#666' },
  val: { flex: 1 },
  li: { marginBottom: 2, paddingLeft: 8 },
  pass: { color: '#0a7d4f' },
  fail: { color: '#c0392b' },
});

function buildDoc(system: any) {
  const meta = RISK_LEVELS[system.riskLevel] || RISK_LEVELS.unclassified;
  const techPct = completionPercentage(system.technicalDocumentation);
  return (
    <Document>
      <Page size="A4" style={s.page}>
        <Text style={s.h1}>EU AI Act — Compliance Evidence Package</Text>
        <Text style={s.meta}>Generated by GrimoireOne · {system.name}</Text>

        <Text style={s.h2}>System</Text>
        <View style={s.row}><Text style={s.label}>Name</Text><Text style={s.val}>{system.name}</Text></View>
        <View style={s.row}><Text style={s.label}>Provider</Text><Text style={s.val}>{system.provider || '—'}</Text></View>
        <View style={s.row}><Text style={s.label}>Role</Text><Text style={s.val}>{system.role || 'provider'}</Text></View>
        <View style={s.row}><Text style={s.label}>Risk level</Text><Text style={s.val}>{meta.label}{system.isGPAI ? ' (GPAI)' : ''}</Text></View>
        <View style={s.row}><Text style={s.label}>Description</Text><Text style={s.val}>{system.description || '—'}</Text></View>

        <Text style={s.h2}>Classification basis (formally derived)</Text>
        {(system.classificationBasis || []).length === 0
          ? <Text style={s.li}>Not yet classified.</Text>
          : system.classificationBasis.map((b: string, i: number) => <Text key={i} style={s.li}>• {b}</Text>)}

        {(system.article50Obligations || []).length > 0 && (
          <>
            <Text style={s.h2}>Article 50 transparency obligations</Text>
            {system.article50Obligations.map((o: string, i: number) => <Text key={i} style={s.li}>• {o}</Text>)}
          </>
        )}

        <Text style={s.h2}>Validation results</Text>
        {(system.validationResults || []).length === 0
          ? <Text style={s.li}>No validations recorded.</Text>
          : system.validationResults.map((v: any, i: number) => (
            <View key={i} style={{ marginBottom: 6 }}>
              <Text style={{ fontFamily: 'Helvetica-Bold', marginBottom: 2 }}>{v.formCode}</Text>
              {(v.description || []).map((d: string, j: number) => (
                <Text key={j} style={[s.li, v.passed?.[j] ? s.pass : s.fail]}>{v.passed?.[j] ? '✓' : '✗'} {d}</Text>
              ))}
            </View>
          ))}

        <Text style={s.h2}>Annex IV technical documentation ({techPct}% complete)</Text>
        {(system.technicalDocumentation || []).map((d: any, i: number) => (
          <Text key={i} style={s.li}>[{d.status === 'completed' ? 'x' : ' '}] {d.title}</Text>
        ))}
      </Page>
    </Document>
  );
}

export function EvidenceExport({ system }: { system: any }) {
  const [busy, setBusy] = useState(false);
  const exportPdf = async () => {
    setBusy(true);
    try {
      const blob = await pdf(buildDoc(system)).toBlob();
      const url = URL.createObjectURL(blob);
      const a = document.createElement('a');
      a.href = url;
      a.download = `${system.name.replace(/[^a-z0-9]+/gi, '-')}-ai-act-evidence.pdf`;
      a.click();
      URL.revokeObjectURL(url);
    } finally {
      setBusy(false);
    }
  };
  return <GhostButton onClick={exportPdf} disabled={busy}>{busy ? <Spinner /> : <Download className="h-4 w-4" />} Export evidence (PDF)</GhostButton>;
}
